### ISSUE TITLE
Code fences create an Internal Server Error if they have "sh" as the language

### ISSUE THREAD

**Issue by quackduck** [hackclub/markdown#8]
To replicate (I've tried this only on [markdown.hackclub.com](https://markdown.hackclub.com)):
1. Open up [markdown.hackclub.com](https://markdown.hackclub.com)
2. Add in this:
````
```sh
foo bar
```
````
3. See "Internal Server Error" appear on the other display and in the Network section of your broswer's debugger

In all other markdown renderers I've used, `sh` is a valid language and so I expected it to be valid Hackclub MD too.

I can see that using `shell` as the language works.

**Comment by quackduck** [comment]
I recently made a workshop. Will it not render correctly on the workshop site if I use `sh` as the language?

**Comment by sampoder** [comment]
I believe that `shell` should be used in this case

**Comment by sampoder** [comment]
For more context: different renderers use different "codes"

**Comment by quackduck** [comment]
Do you mean source code or the language "code"?

**Comment by hyperupcall** [comment]
Both, but "language "code"" is more relevant here. `sh` isn't registered, nor is it used as an alias. (more specifically, `sh` is not a property of `Prism.languages` (since we are using Prism to do the syntax highlighting)

check out this query to see why you can use `shell` (it is an alias of bsah). on the other hand, if you search `Prism.languages.sh`, there will be no results
https://github.com/PrismJS/prism/search?q=Prism.languages.shell

the specific error is this, which is actual internal server error
![image](https://user-images.githubusercontent.com/24364012/103273093-627a7480-49b6-11eb-8078-c22c79955037.png)

**Comment by quackduck** [comment]
Can we add an alias then?

**Comment by hyperupcall** [comment]
although `shell` is a great alternative, i can see how it can cause confusion after pasting in some markdown, expecting everything to work. i think this would be solved easiest by creating a remark plugin to perform a simple ast transform (as opposed to forking `@mapbox/rehype-prism` or something). i'll look into this

**Comment by hyperupcall** [comment]
![image](https://user-images.githubusercontent.com/24364012/103274574-e84bef00-49b9-11eb-8929-e46c9891fc92.png)

So i was able fix using `sh` with a plugin, but that uncovered some weird build system issues (circular dependencies, node-resolve deprecation warnings), which made the build take supppper long. i'll see if i can fix those too
